
name: Deploy FastAPI to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install required system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            swig \
            python3-dev \
            libopenblas-dev \
            libomp-dev

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2  # Updated to the latest version
        with:
          service: my-fastapi-service
          image: gcr.io/scholar-mate-449005/my-fastapi-app:latest
          region: asia-south1
          project_id: scholar-mate-449005
  # Add your Google Cloud Project ID to secrets
